name: Print Pull Request Context
on: workflow_dispatch
permissions:
  pull-requests: read

jobs:
    print-pr-context:
        runs-on: ubuntu-latest
        steps:
          - name: Print context
            run: |
              echo "Pull Request Context:"
              echo "${{ toJson(github.event) }}"

